spring.application.name=web-api
server.port=2025
# Connection to Postgresql
spring.datasource.url=jdbc:postgresql://localhost:5432/web-api
spring.datasource.username=postgres
spring.datasource.password=Kk070809
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresDialect
# Auto create table and update table
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# App Properties
bezkoder.app.jwtSecret= eyJhbGciOiJIUzUxMiJ9eyJhbGciOiJIUzUxMiJ9eyJhbGciOiJIUzUxMiJ9eyJhbGciOiJIUzUxMiJ9eyJhbGciOiJIUzUxMiJ9eyJhbGciOiJIUzUxMiJ9eyJhbGciOiJIUzUxMiJ9eyJhbGciOiJIUzUxMiJ9eyJhbGciOiJIUzUxMiJ9eyJhbGciOiJIUzUxMiJ9eyJhbGciOiJIUzUxMiJ9eyJhbGciOiJIUzUxMiJ9
#bezkoder.app.jwtExpirationMs= 3600000
#bezkoder.app.jwtRefreshExpirationMs= 86400000

## For test
bezkoder.app.jwtExpirationMs= 60000
bezkoder.app.jwtRefreshExpirationMs= 120000
